name: Building and Deploying streamlit and fastapi

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2

      - name: Printing the contents of the project
        run: |
             pwd
             ls -al ~
             ls finalproj/fastapi
             ls finalproj/streamlit
        
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo ${USERNAME}
          echo ${HOSTNAME}
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key -r finalproj ${USER_NAME}@${HOSTNAME}:~/
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/finalproj &&
            
            docker-compose build && docker-compose up -d 
          '
